### ISSUE TITLE
feat: support multiple result sets

### ISSUE THREAD

**Issue by friday** [leo91000/subset-sum#138]
`getSubsetSum([1, 3, 3, 3, 7], 10)` will result in `[ 3, 3, 3, 1 ]`.

But it's not the only solution, and the use case for me is not to find a solution, but all the possible solutions. Since there are duplicate number `3` there's actually 4 answers: `[[3, 7], [3, 7], [3, 7], [1, 3, 3, 3]]`

I am currently using https://github.com/haensl/subset-sum, which supports this, but it's very slow.

**Comment by leo91000** [comment]
> `getSubsetSum([1, 3, 3, 3, 7], 10)` will result in `[ 3, 3, 3, 1 ]`.
> 
> But it's not the only solution, and the use case for me is not to find a solution, but all the possible solutions. Since there are duplicate number `3` there's actually 4 answers: `[[3, 7], [3, 7], [3, 7], [1, 3, 3, 3]]`
> 
> I am currently using https://github.com/haensl/subset-sum, which supports this, but it's very slow.

I have implemented a function `getAllSubsetSums` in `1.2.0`, tell me what you think about it!

**Comment by friday** [comment]
This is perfect! It runs so much faster. The old dependency would run some complex calculations for a very long time and used so much resources it would often crash. Now I try the same ones and they finish instantly with the same answers :star_struck:

Thank you :pray:
